// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUo120_efSX95c4VbrWre5yfJaTrSWbdQ',
    appId: '1:753551413545:web:4bbd5f48cfeb5c6600e738',
    messagingSenderId: '753551413545',
    projectId: 'firebase-sss-training',
    authDomain: 'fir-sss-training.firebaseapp.com',
    storageBucket: 'firebase-sss-training.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAArQcGGcKj1cKJeeBWxVfAtes8s7F7oVA',
    appId: '1:753551413545:android:0f57b03cb421e70100e738',
    messagingSenderId: '753551413545',
    projectId: 'firebase-sss-training',
    storageBucket: 'firebase-sss-training.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhn78nt3bh2-zjF5lEVrx1G4fXuYP4DYU',
    appId: '1:753551413545:ios:c774934f7fc883a700e738',
    messagingSenderId: '753551413545',
    projectId: 'firebase-sss-training',
    storageBucket: 'firebase-sss-training.appspot.com',
    iosClientId: '753551413545-rngrtk9v2215u3um013ng7hkj7obh2bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhn78nt3bh2-zjF5lEVrx1G4fXuYP4DYU',
    appId: '1:753551413545:ios:c774934f7fc883a700e738',
    messagingSenderId: '753551413545',
    projectId: 'firebase-sss-training',
    storageBucket: 'firebase-sss-training.appspot.com',
    iosClientId: '753551413545-rngrtk9v2215u3um013ng7hkj7obh2bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.food',
  );
}
